### ISSUE TITLE
3.0.0-RC2 release

### ISSUE THREAD

**Issue by sake92** [getshaka-org/native-converter#11]
First I wanna say that this is an awesome library! 😃   
When is there gonna be a release for latest scala3?

IDK if you used [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release)?  
It's really easy once you set it up, it publishes a SNAPSHOT on each push to master,  
and a release on each tag (that starts with `v`), e.g. `v0.0.1`.  
Here's an example on one of my projects: https://github.com/sake92/kalem/blob/main/.github/workflows/release.yml

**Comment by AugustNagro** [comment]
Thank you Sakib!

I'll publish for RC2 immediately, and will then look at sbt-ci-release (so lets leave this issue open).

**Comment by AugustNagro** [comment]
Having some trouble, `publish` is failing due to this issue: https://github.com/lampepfl/dotty/issues/11943

Until that is fixed I don't think we can publish for RC2.

**Comment by AugustNagro** [comment]
Blocking issue isn't fixed but Guillaume Martres provided the sbt workaround to skip building doc:

```scala
    // todo remove when fixed: https://github.com/lampepfl/dotty/issues/11943
    Compile / doc / sources := Seq(),
```

v0.4.1 is published now for RC3
