### ISSUE TITLE
Support for Seq

### ISSUE THREAD

**Issue by sake92** [getshaka-org/native-converter#12]
Would be nice to support `Seq[T]` besides List...  
Or at least show a nicer error message than:
```scala
cannot reduce summonFrom with ...
```
Seems like it's not that hard 😄 
https://contributors.scala-lang.org/t/better-cannot-reduce-summonfrom-error-message/4960/6?u=sake92

**Comment by AugustNagro** [comment]
I agree.

Right now there is a given for `scala.collection.Seq` ([here](https://github.com/getshaka-org/native-converter/blob/master/src/main/scala/org/getshaka/nativeconverter/NativeConverter.scala#L287)), but there should be defaults included for everything in Predef too.

Thanks for the link about error messages too.

**Comment by AugustNagro** [comment]
Done!

I added built-in givens for `immutable.{Seq, List, Set, Map}`. I didn't make a custom summonFrom error message, I think we should advocate to make the default message better.

Just published v0.4.1
