### ISSUE TITLE
Recursive structure stackoverflow

### ISSUE THREAD

**Issue by sake92** [getshaka-org/native-converter#16]
This worked fine in 0.4.1 but now does not:
```scala
import org.getshaka.nativeconverter.NativeConverter
import org.junit.Assert.*
import org.junit.Test

class RecursionTests {
  @Test
  def testtt = {
    assertEquals(""" {"statements":[]]} """.trim, Statement.Block(List.empty).toJson)
  }
}

sealed trait Statement derives NativeConverter

object Statement:
  case class Dummy() extends Statement
  case class Block(statements: List[Statement]) extends Statement
```

It throws en error like:

> [info] Fast optimizing C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt
[error] Test RecursionTests.testtt failed: scala.scalajs.js.JavaScriptException: RangeError: Maximum call stack size exceeded, took 0.024999936 sec
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21822)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)
[error]     at Statement$.derived$NativeConverter(C:\projects\sake\native-converter\target\scala-3.0.1\native-converter-test-fastopt\main.js:21826)

**Comment by AugustNagro** [comment]
Thanks for reporting this, I'll take a look soon.

My guess is it's because of


https://github.com/getshaka-org/native-converter/blob/561fb2508a40297346899461294714f54373a6bb/src/main/scala/org/getshaka/nativeconverter/NativeConverter.scala#L377
