### ISSUE TITLE
Run in the JVM with ScalaTest?

### ISSUE THREAD

**Issue by evbo** [getshaka-org/native-converter#21]
I am interested in using Native Converter in unit tests running in the JVM.

In production, all of my code is of course in scalajs, but for speed and debugging it is nice to run unit tests in JVM alone, including ones that verify JSON is being parsed correctly. For instance, what if I accidentally get carried away and put invalid data in some JSON config NativeConverter is expected to parse at runtime? This sort of checking is very valuable when serialized JSON is being committed all the time and want assurances nothing will break in production :)

Is it possible to use native-converter `fromJson` in JVM code? When I try, I am getting:

```scala
[error] -- [E008] Not Found Error: 
[error] 10 |import org.getshaka.nativeconverter.{NativeConverter, fromJson, fromNative}
[error]    |                                                      ^^^^^^^^
[error]    |          value fromJson is not a member of org.getshaka.nativeconverter

```

// my cross project tries to use it like:
```scala
lazy val core = crossProject(JSPlatform, JVMPlatform).crossType(CrossType.Pure).in(file("core"))
  .jsSettings(
    scalaVersion := Dependencies.scalaLangVersion
  )
  .jvmSettings(
    scalaVersion := Dependencies.scalaLangVersion,
    libraryDependencies ++= Seq(
      "org.scala-js" %% "scalajs-stubs" % "1.1.0" % "provided",
      "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test,
      "org.getshaka" %% "native-converter" % Dependencies.shakaVersion % Test
    )
  )
```

I of course can use circe and hope that anything that works with circe probably will work with NativeConverter, but hoping maybe this idea interests the authors too!

**Comment by AugustNagro** [comment]
> Is it possible to use native-converter fromJson in JVM code?

No, NativeConverter is a Scala.js-only library. We do publish a JVM version, but as you can see it's a [no-op](https://github.com/getshaka-org/native-converter/blob/master/jvm/src/main/scala/org/getshaka/nativeconverter/NativeConverter.scala). The reason for this is to support [cross projects](https://github.com/getshaka-org/native-converter-crossproject) where the DTOs are in the `shared` project.

> In production, all of my code is of course in scalajs, but for speed it is nice to run unit tests in JVM alone

How much faster is the performance on JVM? Because in my experience Scala.js is very fast to run tests. And it's generally a good idea to test with the same platform your code is executing on.

If you're trying out Shaka definitely give the [sbt quickstart](https://github.com/getshaka-org/shaka-crossproject.g8) a try! It uses CrossProject.Full instead of Pure.

**Comment by evbo** [comment]
All fair points. Thank you for the thoughtful responses. If no, then I certainly agree it isn't worth the bother. Only reason I thought it might be possible is if all `js` `givens` were easily separable, but I didn't look too closely myself ;)

**Comment by AugustNagro** [comment]
My pleasure. Did you see my comment on https://github.com/getshaka-org/native-converter/issues/20 ? You shouldn't have to explicitly declare any generic givens. You should only ever have to add `derives NativeConverter` to the generic class.

**Comment by evbo** [comment]
I did and will get back to you on that. Also I forgot the # 1 reason I love unit tests in JVM are for debugging when ya need it ;) Maybe some IDE's support debugging scalajs but I have yet to see it.

**Comment by AugustNagro** [comment]
> Maybe some IDE's support debugging scalajs but I have yet to see it.

You can use the chrome debugger for debugging, it works well. Make sure that the sourcemap files Scala.js generated with fastLinkJS are being used/imported. Otherwise the debugger sources look like JS and not Scala.

**Comment by evbo** [comment]
I use devtools for debugging in various browsers, but those don't have IDE integration, as far as I'm aware, for when running unit tests. They are only useful for the bundled app deployed to a dev server or production.

or is there some crazy vs code extension for this I've been missing out on?! :)
